package tui

import (
	"fmt"
	"strings"

	"github.com/jmserra/jsq/internal/db"
)

// sqlLiteral renders a scanned cell value as a SQL literal for the $EDITOR
// starting point. The full path (E) runs the raw SQL the user :wq's, so values
// are inlined here rather than bound: strings are single-quoted with ”
// escaping, nil is NULL, booleans TRUE/FALSE, numerics bare. It only has to be a
// good starting point — the user reviews and fixes it before running.
func sqlLiteral(v any) string {
	switch x := v.(type) {
	case nil:
		return "NULL"
	case bool:
		if x {
			return "TRUE"
		}
		return "FALSE"
	case int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64,
		float32, float64:
		return fmt.Sprintf("%v", x)
	default:
		return "'" + strings.ReplaceAll(fmt.Sprintf("%v", x), "'", "''") + "'"
	}
}

// isStringValue reports whether sqlLiteral will single-quote v (i.e. v is a
// string-ish literal), so the editor can select the text inside the quotes.
func isStringValue(v any) bool {
	switch v.(type) {
	case nil, bool,
		int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64,
		float32, float64:
		return false
	default:
		return true
	}
}

// selectKind tells the editor how to pre-select the value under the cursor.
type selectKind int

const (
	selectNone         selectKind = iota // just place the cursor (empty / multi-line)
	selectToken                          // whole literal to end of line (NULL / number)
	selectInsideQuotes                   // the text between a string literal's quotes
)

// editorSeed is a generated statement plus where to put the cursor, so the
// editor can open on the value (and, for a single value, pre-select it).
type editorSeed struct {
	sql  string
	line int // 1-based cursor line (0 = leave at top)
	col  int // 1-based byte column to place the cursor
	kind selectKind
}

// buildUpdateStmt is the E full-path starting point (the editing model in
// README): a full-PK-keyed UPDATE with the current value inlined at the end of
// the SET line so the editor can drop you straight onto it. To set NULL, change
// the value to a bare NULL; to abort, clear the buffer or :q!.
func buildUpdateStmt(eng db.Engine, table db.TableRef, col string, val any, keys []keyPred) editorSeed {
	lit := sqlLiteral(val)
	setLine := fmt.Sprintf("UPDATE %s SET %s = %s",
		eng.QualifiedName(table), eng.QuoteIdent(col), lit)
	litStart := len(setLine) - len(lit) + 1 // 1-based byte col of the literal

	preds := make([]string, len(keys))
	for i, k := range keys {
		preds[i] = eng.QuoteIdent(k.col) + " = " + sqlLiteral(k.val)
	}
	sql := setLine + "\nWHERE " + strings.Join(preds, " AND ") + ";\n"

	seed := editorSeed{sql: sql, line: 1, col: litStart, kind: selectToken}
	switch {
	case strings.Contains(lit, "\n"):
		seed.kind = selectNone // multi-line value: land on it, don't select
	case isStringValue(val):
		if len(lit) > 2 { // non-empty '...'
			seed.col = litStart + 1 // first char inside the quotes
			seed.kind = selectInsideQuotes
		} else { // empty '' — nothing to select, sit between the quotes
			seed.col = litStart + 1
			seed.kind = selectNone
		}
	}
	return seed
}

// buildInsertStmt is the o (blank insert) starting point — and the base for p
// (duplicate) later. It inserts the insertable columns (auto-generated ones are
// omitted so the DB assigns them), one NULL per line with a trailing `-- col`
// and an annotation: a ⚠ on columns likely to collide (PK / UNIQUE), surfaced
// before :wq rather than as a post-hoc DB error, or a note that a column has a
// default (delete the line to use it). Values are seeded NULL rather than with
// the DEFAULT keyword, which SQLite doesn't accept in a VALUES list. The cursor
// lands on the first value.
func buildInsertStmt(eng db.Engine, table db.TableRef, cols []db.Column) editorSeed {
	type vline struct{ val, col, warn string }
	var names []string
	var lines []vline
	for _, c := range cols {
		if c.AutoGenerated {
			continue // DB assigns it
		}
		names = append(names, eng.QuoteIdent(c.Name))
		warn := ""
		switch {
		case c.PrimaryKey:
			warn = "⚠ PRIMARY KEY — must be unique"
		case c.Unique:
			warn = "⚠ UNIQUE"
		case c.HasDefault:
			warn = "has default — delete this line to use it"
		}
		lines = append(lines, vline{val: "NULL", col: c.Name, warn: warn})
	}

	// A table with only auto-generated columns has no value list to fill.
	if len(names) == 0 {
		return editorSeed{sql: fmt.Sprintf("INSERT INTO %s DEFAULT VALUES;\n", eng.QualifiedName(table))}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "INSERT INTO %s (%s)\nVALUES (\n", eng.QualifiedName(table), strings.Join(names, ", "))
	maxw := 0
	cells := make([]string, len(lines))
	for i, l := range lines {
		cells[i] = l.val
		if i < len(lines)-1 {
			cells[i] += ","
		}
		if len(cells[i]) > maxw {
			maxw = len(cells[i])
		}
	}
	for i, l := range lines {
		comment := "-- " + l.col
		if l.warn != "" {
			comment += "   " + l.warn
		}
		fmt.Fprintf(&b, "  %s%s%s\n", cells[i], strings.Repeat(" ", maxw-len(cells[i])+1), comment)
	}
	b.WriteString(");\n")

	// Cursor on the first value (line 3: INSERT, VALUES(, then values), indented 2.
	return editorSeed{sql: b.String(), line: 3, col: 3, kind: selectNone}
}

// buildDeleteStmt is the D full-path starting point: a full-PK-keyed DELETE for
// the current row, opened in $EDITOR for review — :wq confirms and runs it, :q!
// (or an emptied buffer) aborts. Never a bare DELETE.
func buildDeleteStmt(eng db.Engine, table db.TableRef, keys []keyPred) editorSeed {
	preds := make([]string, len(keys))
	for i, k := range keys {
		preds[i] = eng.QuoteIdent(k.col) + " = " + sqlLiteral(k.val)
	}
	sql := fmt.Sprintf("DELETE FROM %s WHERE %s;\n", eng.QualifiedName(table), strings.Join(preds, " AND "))
	return editorSeed{sql: sql, line: 1, col: 1, kind: selectNone}
}

// stripSQLComments drops -- line comments and blank lines. Used only to detect an
// emptied editor buffer (cleared → abort); the statement that actually runs is
// the file's full contents.
func stripSQLComments(s string) string {
	var b strings.Builder
	for _, line := range strings.Split(s, "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "--") {
			continue
		}
		b.WriteString(t)
		b.WriteByte('\n')
	}
	return b.String()
}
