// Package db is the single abstraction over a database engine (see README.md).
// First slice implements SQLite; Postgres/MySQL are stubbed at Open.
package db

import (
	"context"
	"database/sql"
	"fmt"
	"net"
	"net/url"
	"strings"
)

// Table identifies a table, optionally schema-qualified.
type Table struct {
	Schema string
	Name   string
}

// Ref converts a Table to a TableRef.
func (t Table) Ref() TableRef { return TableRef{Schema: t.Schema, Name: t.Name} }

// TableRef references a table for introspection/queries.
type TableRef struct {
	Schema string
	Name   string
}

// Column is enriched metadata for a table column.
type Column struct {
	Name          string
	Type          string
	PrimaryKey    bool
	AutoGenerated bool // serial / identity / auto_increment / sqlite rowid alias
	HasDefault    bool
	Unique        bool
}

// ForeignKey is one foreign-key constraint: the local Columns reference
// RefTable's RefColumns (parallel slices — one entry per column, so a composite
// key has len>1). Used to follow a value to the row it points at.
type ForeignKey struct {
	Columns    []string
	RefTable   TableRef
	RefColumns []string
}

// User is a database user (Postgres: a role). Host is MySQL's other half of the
// account identity — an account is 'bob'@'%', and two rows with the same name
// but different hosts are two different users with their own privileges.
// Postgres roles have no host, so it stays empty there.
type User struct {
	Name string
	Host string
}

// Label is the display form: "bob@%" on MySQL, plain "bob" on Postgres.
func (u User) Label() string {
	if u.Host == "" {
		return u.Name
	}
	return u.Name + "@" + u.Host
}

// Grant is one row of the grants view: what a user may do (Privilege) over what
// (Scope + Object). It is the tuple GrantsSQL emits and RevokeSQL consumes, so a
// row under the cursor is directly actionable.
type Grant struct {
	Scope     string // global | attribute | role | database | schema | table | column
	Object    string // what it applies to; empty for a global/attribute row
	Privilege string
}

// ResultSet is a query result. A nil Rows element is SQL NULL.
type ResultSet struct {
	Cols  []string
	Rows  [][]any
	Table *TableRef    // set when the query was a plain single-table select
	PK    []string     // PK column names, when known
	FKs   []ForeignKey // foreign keys on the table: header marker + in-place follow
}

// Engine is the one abstraction the TUI talks to.
type Engine interface {
	Tables(ctx context.Context) ([]Table, error)
	Columns(ctx context.Context, t TableRef) ([]Column, error)
	PrimaryKey(ctx context.Context, t TableRef) ([]string, error)
	ForeignKeys(ctx context.Context, t TableRef) ([]ForeignKey, error)
	Query(ctx context.Context, query string, args ...any) (*ResultSet, error)
	Exec(ctx context.Context, query string, args ...any) (int64, error)
	Databases(ctx context.Context) ([]string, error) // deferred picker; may be nil

	// ProcessListSQL is the read that lists the server's current sessions, run
	// as an ordinary ad-hoc query. Empty when the engine has no such notion
	// (SQLite), which the caller reports rather than running.
	ProcessListSQL() string

	// Users lists the server's users/roles for the `u` picker. Nil when the
	// engine has no such notion (SQLite), which the caller reports.
	Users(ctx context.Context) ([]User, error)

	// GrantsSQL returns the read that lists u's privileges, with its bind args —
	// run as an ordinary ad-hoc query, so `r` re-runs it unchanged. It takes a
	// ctx because an engine may probe what its server exposes before composing
	// the query (MySQL's role/dynamic-privilege tables are version- and
	// privilege-dependent). Empty SQL means the engine has no users at all.
	//
	// Every engine normalises to the same four columns — scope, object,
	// privilege, grantable — so one result shape covers both dialects:
	//
	//	global    │                  │ SELECT         │ NO
	//	role      │ readonly         │ MEMBER         │ NO
	//	database  │ appdb            │ ALL PRIVILEGES │ NO
	//	table     │ appdb.orders     │ UPDATE         │ NO
	//
	// with Postgres adding `attribute` rows (SUPERUSER, LOGIN, …) for the role
	// flags that are its equivalent of a global privilege.
	GrantsSQL(ctx context.Context, u User) (string, []any, error)

	// GrantSQL is the starting point for granting more to an existing user: a
	// template scoped to dbName, opened in $EDITOR and run verbatim like
	// CreateUserSQL. Empty when the engine has no users.
	GrantSQL(u User, dbName string) string

	// RevokeSQL is the statement that takes back one row of the grants view — the
	// reverse of the grant the row describes. Empty when the row is not something
	// this dialect can revoke (an unknown scope), which the caller reports.
	//
	// The Grant comes back through the grid as the text this engine's GrantsSQL
	// put there, so parsing a composite Object (a "db.table") is the inverse of
	// the CONCAT that built it. An identifier containing a dot therefore splits
	// wrong — acceptable because the result is a SEED: it opens in $EDITOR for
	// review, and is never run unseen.
	RevokeSQL(u User, g Grant) string

	// DropUserSQL is the statement that removes a user, opened in $EDITOR like the
	// rest of the full path — never run on a keystroke. Empty when the engine has
	// no users.
	DropUserSQL(u User) string

	// CreateUserSQL is the starting point for creating a user: the statements a
	// new account normally needs, written the way this dialect writes them, with
	// name as the placeholder to replace and dbName the database to scope the
	// grant to (unscoped when empty). It is a TEMPLATE, opened in $EDITOR and run
	// verbatim once the user has edited it — jsq never composes a CREATE USER of
	// its own. Empty when the engine has no users (SQLite).
	CreateUserSQL(name, dbName string) string

	QuoteIdent(s string) string
	QualifiedName(t TableRef) string // schema-qualified, quoted table name
	Placeholder(i int) string
	FilterPredicate(quotedCol string, i int) string
	Close() error
}

// Open infers the engine from a URL scheme or file path and connects.
func Open(ctx context.Context, dsn string) (Engine, error) {
	switch EngineOf(dsn) {
	case "sqlite":
		return openSQLite(ctx, dsn)
	case "postgres":
		return openPostgres(ctx, dsn)
	case "mysql":
		return openMySQL(ctx, dsn)
	default:
		return nil, fmt.Errorf("cannot determine engine for %q", dsn)
	}
}

// stdEngine is the shared database/sql plumbing embedded by every engine: the
// dialect-agnostic Query/Exec/Close over a *sql.DB. Each engine embeds it and
// implements only its dialect methods (quoting, placeholders, introspection).
type stdEngine struct{ db *sql.DB }

func (e *stdEngine) Query(ctx context.Context, query string, args ...any) (*ResultSet, error) {
	return scanQuery(ctx, e.db, query, args...)
}

func (e *stdEngine) Exec(ctx context.Context, query string, args ...any) (int64, error) {
	res, err := e.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

func (e *stdEngine) Close() error { return e.db.Close() }

// openStd opens a database/sql handle for driver+dsn and verifies it with a
// ping, closing it and wrapping the failure with label on error. Shared by the
// three engine openers so the open/ping/wrap dance lives in one place.
func openStd(ctx context.Context, driver, dsn, label string) (*sql.DB, error) {
	sdb, err := sql.Open(driver, dsn)
	if err != nil {
		return nil, err
	}
	if err := sdb.PingContext(ctx); err != nil {
		sdb.Close()
		return nil, fmt.Errorf("%s: %w", label, err)
	}
	return sdb, nil
}

// namesToTables wraps bare table names (from a single-schema engine) as Tables.
func namesToTables(names []string) []Table {
	out := make([]Table, len(names))
	for i, n := range names {
		out[i] = Table{Name: n}
	}
	return out
}

// scanQuery runs a query and scans all rows into a ResultSet ([]byte → string,
// nil preserved as SQL NULL). Shared by the engine implementations.
func scanQuery(ctx context.Context, sdb *sql.DB, query string, args ...any) (*ResultSet, error) {
	rows, err := sdb.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	rs := &ResultSet{Cols: cols}
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return nil, err
		}
		for i, v := range vals {
			if b, ok := v.([]byte); ok {
				vals[i] = string(b)
			}
		}
		rs.Rows = append(rs.Rows, vals)
	}
	return rs, rows.Err()
}

// queryStrings runs a single-column query and collects the column into a slice —
// the shared shape behind Databases/Tables/PrimaryKey and the unique-column
// lookups, which otherwise repeat the same Next/Scan/Err boilerplate per engine.
func queryStrings(ctx context.Context, sdb *sql.DB, query string, args ...any) ([]string, error) {
	rows, err := sdb.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			return nil, err
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// cutDot splits a composite object name ("db.table") at its FIRST dot. Used to
// unpick the Object of a grants row back into its parts — see RevokeSQL on the
// dotted-identifier caveat.
func cutDot(s string) (head, tail string) {
	if i := strings.Index(s, "."); i >= 0 {
		return s[:i], s[i+1:]
	}
	return s, ""
}

// quoteIdentDouble quotes an identifier with double-quotes, doubling any embedded
// ones — the standard-SQL form shared by Postgres and SQLite (MySQL uses
// backticks, so it quotes its own way).
func quoteIdentDouble(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

// fkAccum groups the per-column rows of a foreign-key introspection query into
// ForeignKeys, preserving both first-seen constraint order and (within a
// composite key) the scan order of the columns. Every engine's ForeignKeys walks
// parallel (column, ref-column) rows keyed by a constraint identifier; this is
// that shared assembly. Callers scan a row, then add() it under the constraint's
// key with the referenced table (set once, from the first row of the group).
type fkAccum struct {
	byKey map[string]*ForeignKey
	order []string
}

func (a *fkAccum) add(key string, ref TableRef, col, refCol string) {
	if a.byKey == nil {
		a.byKey = map[string]*ForeignKey{}
	}
	fk := a.byKey[key]
	if fk == nil {
		fk = &ForeignKey{RefTable: ref}
		a.byKey[key] = fk
		a.order = append(a.order, key)
	}
	fk.Columns = append(fk.Columns, col)
	fk.RefColumns = append(fk.RefColumns, refCol)
}

// ordered returns the accumulated keys in first-seen order, as pointers so a
// caller can still post-process each group (e.g. sqlite's implicit-PK fill).
func (a *fkAccum) ordered() []*ForeignKey {
	out := make([]*ForeignKey, 0, len(a.order))
	for _, k := range a.order {
		out = append(out, a.byKey[k])
	}
	return out
}

// result is ordered() flattened to values, for engines with nothing to fix up.
func (a *fkAccum) result() []ForeignKey {
	out := make([]ForeignKey, 0, len(a.order))
	for _, fk := range a.ordered() {
		out = append(out, *fk)
	}
	return out
}

// DatabaseName derives the database name for the header: the URL path for
// server engines, or the file's base name (sans extension) for SQLite.
func DatabaseName(dsn string) string {
	if u, err := url.Parse(dsn); err == nil && u.Scheme != "" {
		switch u.Scheme {
		case "postgres", "postgresql", "mysql":
			return strings.TrimPrefix(u.Path, "/")
		}
	}
	base := sqlitePath(dsn)
	if i := strings.LastIndexAny(base, `/\`); i >= 0 {
		base = base[i+1:]
	}
	if i := strings.LastIndex(base, "."); i > 0 {
		base = base[:i]
	}
	return base
}

// HostPort returns the TCP host:port a server DSN connects to, applying the
// scheme's default port when the URL omits it. It is "" for SQLite or any DSN
// without a network host — used to wait for a `cmd` tunnel before connecting.
func HostPort(dsn string) string {
	u, err := url.Parse(dsn)
	if err != nil || u.Scheme == "" {
		return ""
	}
	host := u.Hostname()
	if host == "" {
		return ""
	}
	port := u.Port()
	switch u.Scheme {
	case "postgres", "postgresql":
		if port == "" {
			port = "5432"
		}
	case "mysql":
		if port == "" {
			port = "3306"
		}
	default:
		return ""
	}
	return net.JoinHostPort(host, port)
}

// WithDatabase returns dsn pointing at a different database on the same server
// (host, credentials and query params preserved) — used to jump databases. For
// SQLite (a database is a file) it returns dsn unchanged.
func WithDatabase(dsn, dbname string) string {
	u, err := url.Parse(dsn)
	if err != nil || u.Scheme == "" {
		return dsn
	}
	switch u.Scheme {
	case "postgres", "postgresql", "mysql":
		u.Path = "/" + dbname
		return u.String()
	}
	return dsn
}

// EngineOf returns "sqlite" | "postgres" | "mysql" | "" for a DSN or path.
func EngineOf(dsn string) string {
	if u, err := url.Parse(dsn); err == nil && u.Scheme != "" {
		switch u.Scheme {
		case "postgres", "postgresql":
			return "postgres"
		case "mysql":
			return "mysql"
		case "sqlite", "sqlite3", "file":
			return "sqlite"
		}
	}
	// No scheme: a bare filesystem path → SQLite.
	if dsn != "" && !strings.Contains(dsn, "://") {
		return "sqlite"
	}
	return ""
}
