// Package db is the single abstraction over a database engine (see README.md).
// First slice implements SQLite; Postgres/MySQL are stubbed at Open.
package db

import (
	"context"
	"database/sql"
	"fmt"
	"net/url"
	"strings"
)

// Table identifies a table, optionally schema-qualified.
type Table struct {
	Schema string
	Name   string
}

// Ref converts a Table to a TableRef.
func (t Table) Ref() TableRef { return TableRef{Schema: t.Schema, Name: t.Name} }

// TableRef references a table for introspection/queries.
type TableRef struct {
	Schema string
	Name   string
}

// Column is enriched metadata for a table column.
type Column struct {
	Name          string
	Type          string
	Nullable      bool
	PrimaryKey    bool
	AutoGenerated bool // serial / identity / auto_increment / sqlite rowid alias
	HasDefault    bool
	Default       string
	Unique        bool
}

// ResultSet is a query result. A nil Rows element is SQL NULL.
type ResultSet struct {
	Cols  []string
	Rows  [][]any
	Table *TableRef // set when the query was a plain single-table select
	PK    []string  // PK column names, when known
}

// Engine is the one abstraction the TUI talks to.
type Engine interface {
	Tables(ctx context.Context) ([]Table, error)
	Columns(ctx context.Context, t TableRef) ([]Column, error)
	PrimaryKey(ctx context.Context, t TableRef) ([]string, error)
	Query(ctx context.Context, query string, args ...any) (*ResultSet, error)
	Exec(ctx context.Context, query string, args ...any) (int64, error)
	Databases(ctx context.Context) ([]string, error) // deferred picker; may be nil

	QuoteIdent(s string) string
	QualifiedName(t TableRef) string // schema-qualified, quoted table name
	Placeholder(i int) string
	UsesSchemas() bool
	FilterPredicate(quotedCol string, i int) string
	Close() error
}

// openConfig holds the resolved Open options.
type openConfig struct{ readOnly bool }

// Option customizes Open.
type Option func(*openConfig)

// ReadOnly, when ro is true, opens the connection so the database itself refuses
// every write — a session-level backstop for the TUI's app-layer read_only guard
// (which only classifies by leading keyword and so can't catch EXPLAIN ANALYZE
// <DML>, a volatile function inside a SELECT, a write PRAGMA, etc.). Each engine
// enforces it with its native mechanism (see the open* funcs).
func ReadOnly(ro bool) Option { return func(c *openConfig) { c.readOnly = ro } }

// Open infers the engine from a URL scheme or file path and connects.
func Open(ctx context.Context, dsn string, opts ...Option) (Engine, error) {
	var cfg openConfig
	for _, o := range opts {
		o(&cfg)
	}
	switch EngineOf(dsn) {
	case "sqlite":
		return openSQLite(ctx, dsn, cfg.readOnly)
	case "postgres":
		return openPostgres(ctx, dsn, cfg.readOnly)
	case "mysql":
		return openMySQL(ctx, dsn, cfg.readOnly)
	default:
		return nil, fmt.Errorf("cannot determine engine for %q", dsn)
	}
}

// scanQuery runs a query and scans all rows into a ResultSet ([]byte → string,
// nil preserved as SQL NULL). Shared by the engine implementations.
func scanQuery(ctx context.Context, sdb *sql.DB, query string, args ...any) (*ResultSet, error) {
	rows, err := sdb.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	rs := &ResultSet{Cols: cols}
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return nil, err
		}
		for i, v := range vals {
			if b, ok := v.([]byte); ok {
				vals[i] = string(b)
			}
		}
		rs.Rows = append(rs.Rows, vals)
	}
	return rs, rows.Err()
}

// DatabaseName derives the database name for the header: the URL path for
// server engines, or the file's base name (sans extension) for SQLite.
func DatabaseName(dsn string) string {
	if u, err := url.Parse(dsn); err == nil && u.Scheme != "" {
		switch u.Scheme {
		case "postgres", "postgresql", "mysql":
			return strings.TrimPrefix(u.Path, "/")
		}
	}
	base := sqlitePath(dsn)
	if i := strings.LastIndexAny(base, `/\`); i >= 0 {
		base = base[i+1:]
	}
	if i := strings.LastIndex(base, "."); i > 0 {
		base = base[:i]
	}
	return base
}

// EngineOf returns "sqlite" | "postgres" | "mysql" | "" for a DSN or path.
func EngineOf(dsn string) string {
	if u, err := url.Parse(dsn); err == nil && u.Scheme != "" {
		switch u.Scheme {
		case "postgres", "postgresql":
			return "postgres"
		case "mysql":
			return "mysql"
		case "sqlite", "sqlite3", "file":
			return "sqlite"
		}
	}
	// No scheme: a bare filesystem path → SQLite.
	if dsn != "" && !strings.Contains(dsn, "://") {
		return "sqlite"
	}
	return ""
}
