package db

import (
	"context"
	"net/url"
	"os"
	"testing"
)

// TestMySQLLive exercises the driver against a live database. Set
// JSQ_TEST_MYSQL_DB (and optionally _USER/_PASS/_HOST) to run it.
func TestMySQLLive(t *testing.T) {
	dbName := os.Getenv("JSQ_TEST_MYSQL_DB")
	if dbName == "" {
		t.Skip("set JSQ_TEST_MYSQL_DB to run the live mysql test")
	}
	host := os.Getenv("JSQ_TEST_MYSQL_HOST")
	if host == "" {
		host = "127.0.0.1:3306"
	}
	u := url.URL{Scheme: "mysql", Host: host, Path: "/" + dbName}
	if user := os.Getenv("JSQ_TEST_MYSQL_USER"); user != "" {
		u.User = url.UserPassword(user, os.Getenv("JSQ_TEST_MYSQL_PASS"))
	}

	ctx := context.Background()
	e, err := Open(ctx, u.String())
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer e.Close()

	tables, err := e.Tables(ctx)
	if err != nil {
		t.Fatalf("tables: %v", err)
	}
	t.Logf("%d tables", len(tables))
	if len(tables) == 0 {
		return
	}
	first := tables[0]
	cols, err := e.Columns(ctx, first.Ref())
	if err != nil {
		t.Fatalf("columns(%s): %v", first.Name, err)
	}
	t.Logf("columns of %s:", first.Name)
	for i, c := range cols {
		if i >= 10 {
			t.Logf("  … (%d more)", len(cols)-10)
			break
		}
		t.Logf("  %-24s %-14s pk=%-5v auto=%-5v null=%v", c.Name, c.Type, c.PrimaryKey, c.AutoGenerated, c.Nullable)
	}
	pk, err := e.PrimaryKey(ctx, first.Ref())
	if err != nil {
		t.Fatalf("pk: %v", err)
	}
	t.Logf("primary key: %v", pk)

	rs, err := e.Query(ctx, "SELECT * FROM "+e.QualifiedName(first.Ref())+" LIMIT 3")
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	t.Logf("sample query → %d cols, %d rows", len(rs.Cols), len(rs.Rows))
}
