package db

import (
	"context"
	"database/sql"
	"fmt"
	"net"
	"net/url"
	"strings"

	"github.com/go-sql-driver/mysql" // registers the "mysql" driver
)

type myEngine struct {
	db *sql.DB
}

func openMySQL(ctx context.Context, rawurl string) (Engine, error) {
	dsn, err := mysqlDSN(rawurl)
	if err != nil {
		return nil, err
	}
	sdb, err := sql.Open("mysql", dsn)
	if err != nil {
		return nil, err
	}
	if err := sdb.PingContext(ctx); err != nil {
		sdb.Close()
		return nil, fmt.Errorf("connecting to mysql: %w", err)
	}
	return &myEngine{db: sdb}, nil
}

// mysqlDSN converts a mysql:// URL into the go-sql-driver DSN, using the
// driver's own Config so passwords/params are escaped correctly.
func mysqlDSN(rawurl string) (string, error) {
	u, err := url.Parse(rawurl)
	if err != nil {
		return "", err
	}
	cfg := mysql.NewConfig()
	cfg.Net = "tcp"
	host := u.Host
	if host == "" {
		host = "127.0.0.1:3306"
	} else if _, _, err := net.SplitHostPort(host); err != nil {
		// No port (SplitHostPort errors) → default it. JoinHostPort re-brackets an
		// IPv6 literal, so `[::1]` and bare hostnames both work (the old substring
		// `:` check mistook an IPv6 host for one that already had a port).
		host = net.JoinHostPort(strings.Trim(host, "[]"), "3306")
	}
	cfg.Addr = host
	cfg.DBName = strings.TrimPrefix(u.Path, "/")
	if u.User != nil {
		cfg.User = u.User.Username()
		if pw, ok := u.User.Password(); ok {
			cfg.Passwd = pw
		}
	}
	if q := u.Query(); len(q) > 0 {
		cfg.Params = map[string]string{}
		for k := range q {
			cfg.Params[k] = q.Get(k)
		}
	}
	return cfg.FormatDSN(), nil
}

func (e *myEngine) Close() error           { return e.db.Close() }
func (e *myEngine) Placeholder(int) string { return "?" }

func (e *myEngine) QuoteIdent(s string) string {
	return "`" + strings.ReplaceAll(s, "`", "``") + "`"
}

func (e *myEngine) QualifiedName(t TableRef) string { return e.QuoteIdent(t.Name) }

func (e *myEngine) FilterPredicate(quotedCol string, _ int) string {
	return fmt.Sprintf("LOWER(CAST(%s AS CHAR)) LIKE LOWER(?)", quotedCol)
}

func (e *myEngine) Databases(ctx context.Context) ([]string, error) {
	return queryStrings(ctx, e.db, `
		SELECT schema_name FROM information_schema.schemata
		WHERE schema_name NOT IN ('information_schema','mysql','performance_schema','sys')
		ORDER BY schema_name`)
}

func (e *myEngine) Tables(ctx context.Context) ([]Table, error) {
	names, err := queryStrings(ctx, e.db, `
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE'
		ORDER BY table_name`)
	if err != nil {
		return nil, err
	}
	out := make([]Table, len(names))
	for i, n := range names {
		out[i] = Table{Name: n}
	}
	return out, nil
}

func (e *myEngine) Columns(ctx context.Context, t TableRef) ([]Column, error) {
	unique, err := e.uniqueColumns(ctx, t)
	if err != nil {
		return nil, err
	}
	rows, err := e.db.QueryContext(ctx, `
		SELECT column_name, data_type, is_nullable, column_default, extra, column_key
		FROM information_schema.columns
		WHERE table_schema = DATABASE() AND table_name = ?
		ORDER BY ordinal_position`, t.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []Column
	for rows.Next() {
		var name, dtype, nullable, extra, key string
		var dflt sql.NullString
		if err := rows.Scan(&name, &dtype, &nullable, &dflt, &extra, &key); err != nil {
			return nil, err
		}
		cols = append(cols, Column{
			Name:          name,
			Type:          dtype,
			PrimaryKey:    key == "PRI",
			Unique:        unique[name],
			AutoGenerated: strings.Contains(extra, "auto_increment"),
			HasDefault:    dflt.Valid,
		})
	}
	return cols, rows.Err()
}

// uniqueColumns returns every column covered by a unique index (PRIMARY included).
// column_key only flags the leading column of a composite unique index, so a
// UNIQUE(a,b) would leave b unflagged — statistics.non_unique=0 covers all of them,
// matching how pg/sqlite mark every covered column.
func (e *myEngine) uniqueColumns(ctx context.Context, t TableRef) (map[string]bool, error) {
	names, err := queryStrings(ctx, e.db, `
		SELECT column_name FROM information_schema.statistics
		WHERE table_schema = DATABASE() AND table_name = ? AND non_unique = 0`, t.Name)
	if err != nil {
		return nil, err
	}
	out := make(map[string]bool, len(names))
	for _, n := range names {
		out[n] = true
	}
	return out, nil
}

// PrimaryKey reads just the PK columns from key_column_usage — deliberately not
// via Columns, which pulls column_default/extra and (in composite order) is
// heavier. PrimaryKey is on the hot path (every load and scroll fetch).
func (e *myEngine) PrimaryKey(ctx context.Context, t TableRef) ([]string, error) {
	return queryStrings(ctx, e.db, `
		SELECT column_name
		FROM information_schema.key_column_usage
		WHERE table_schema = DATABASE() AND table_name = ?
		  AND constraint_name = 'PRIMARY'
		ORDER BY ordinal_position`, t.Name)
}

// ForeignKeys reads FK constraints from key_column_usage (rows carrying a
// referenced_table_name), grouped by constraint name and ordered within a
// composite key by ordinal_position. Single-DB, so the ref table has no schema.
func (e *myEngine) ForeignKeys(ctx context.Context, t TableRef) ([]ForeignKey, error) {
	rows, err := e.db.QueryContext(ctx, `
		SELECT constraint_name, column_name, referenced_table_name, referenced_column_name
		FROM information_schema.key_column_usage
		WHERE table_schema = DATABASE() AND table_name = ?
		  AND referenced_table_name IS NOT NULL
		ORDER BY constraint_name, ordinal_position`, t.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var acc fkAccum
	for rows.Next() {
		var name, col, refTable, refCol string
		if err := rows.Scan(&name, &col, &refTable, &refCol); err != nil {
			return nil, err
		}
		acc.add(name, TableRef{Name: refTable}, col, refCol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return acc.result(), nil
}

func (e *myEngine) Query(ctx context.Context, query string, args ...any) (*ResultSet, error) {
	return scanQuery(ctx, e.db, query, args...)
}

func (e *myEngine) Exec(ctx context.Context, query string, args ...any) (int64, error) {
	res, err := e.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
