package db

import (
	"context"
	"database/sql"
	"fmt"
	"net/url"
	"strings"

	"github.com/go-sql-driver/mysql" // registers the "mysql" driver
)

type myEngine struct {
	db *sql.DB
}

func openMySQL(ctx context.Context, rawurl string) (Engine, error) {
	dsn, err := mysqlDSN(rawurl)
	if err != nil {
		return nil, err
	}
	sdb, err := sql.Open("mysql", dsn)
	if err != nil {
		return nil, err
	}
	if err := sdb.PingContext(ctx); err != nil {
		sdb.Close()
		return nil, fmt.Errorf("connecting to mysql: %w", err)
	}
	return &myEngine{db: sdb}, nil
}

// mysqlDSN converts a mysql:// URL into the go-sql-driver DSN, using the
// driver's own Config so passwords/params are escaped correctly.
func mysqlDSN(rawurl string) (string, error) {
	u, err := url.Parse(rawurl)
	if err != nil {
		return "", err
	}
	cfg := mysql.NewConfig()
	cfg.Net = "tcp"
	host := u.Host
	if host == "" {
		host = "127.0.0.1:3306"
	}
	if !strings.Contains(host, ":") {
		host += ":3306"
	}
	cfg.Addr = host
	cfg.DBName = strings.TrimPrefix(u.Path, "/")
	if u.User != nil {
		cfg.User = u.User.Username()
		if pw, ok := u.User.Password(); ok {
			cfg.Passwd = pw
		}
	}
	if q := u.Query(); len(q) > 0 {
		cfg.Params = map[string]string{}
		for k := range q {
			cfg.Params[k] = q.Get(k)
		}
	}
	return cfg.FormatDSN(), nil
}

func (e *myEngine) Close() error             { return e.db.Close() }
func (e *myEngine) UsesSchemas() bool        { return false }
func (e *myEngine) Placeholder(int) string   { return "?" }

func (e *myEngine) QuoteIdent(s string) string {
	return "`" + strings.ReplaceAll(s, "`", "``") + "`"
}

func (e *myEngine) QualifiedName(t TableRef) string { return e.QuoteIdent(t.Name) }

func (e *myEngine) FilterPredicate(quotedCol string, _ int) string {
	return fmt.Sprintf("LOWER(CAST(%s AS CHAR)) LIKE LOWER(?)", quotedCol)
}

func (e *myEngine) Databases(ctx context.Context) ([]string, error) {
	rows, err := e.db.QueryContext(ctx, `
		SELECT schema_name FROM information_schema.schemata
		WHERE schema_name NOT IN ('information_schema','mysql','performance_schema','sys')
		ORDER BY schema_name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			return nil, err
		}
		out = append(out, n)
	}
	return out, rows.Err()
}

func (e *myEngine) Tables(ctx context.Context) ([]Table, error) {
	rows, err := e.db.QueryContext(ctx, `
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE'
		ORDER BY table_name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Table
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			return nil, err
		}
		out = append(out, Table{Name: n})
	}
	return out, rows.Err()
}

func (e *myEngine) Columns(ctx context.Context, t TableRef) ([]Column, error) {
	rows, err := e.db.QueryContext(ctx, `
		SELECT column_name, data_type, is_nullable, column_default, extra, column_key
		FROM information_schema.columns
		WHERE table_schema = DATABASE() AND table_name = ?
		ORDER BY ordinal_position`, t.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []Column
	for rows.Next() {
		var name, dtype, nullable, extra, key string
		var dflt sql.NullString
		if err := rows.Scan(&name, &dtype, &nullable, &dflt, &extra, &key); err != nil {
			return nil, err
		}
		cols = append(cols, Column{
			Name:          name,
			Type:          dtype,
			Nullable:      nullable == "YES",
			PrimaryKey:    key == "PRI",
			AutoGenerated: strings.Contains(extra, "auto_increment"),
			HasDefault:    dflt.Valid,
			Default:       dflt.String,
		})
	}
	return cols, rows.Err()
}

func (e *myEngine) PrimaryKey(ctx context.Context, t TableRef) ([]string, error) {
	cols, err := e.Columns(ctx, t)
	if err != nil {
		return nil, err
	}
	var pk []string
	for _, c := range cols {
		if c.PrimaryKey {
			pk = append(pk, c.Name)
		}
	}
	return pk, nil
}

func (e *myEngine) Query(ctx context.Context, query string, args ...any) (*ResultSet, error) {
	return scanQuery(ctx, e.db, query, args...)
}

func (e *myEngine) Exec(ctx context.Context, query string, args ...any) (int64, error) {
	res, err := e.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
