package db

import (
	"context"
	"os"
	"testing"
)

// TestPostgresLive exercises the real driver against a live database. Set
// JSQ_TEST_PG to a DSN to run it; otherwise it is skipped.
func TestPostgresLive(t *testing.T) {
	dsn := os.Getenv("JSQ_TEST_PG")
	if dsn == "" {
		t.Skip("set JSQ_TEST_PG to run the live postgres test")
	}
	ctx := context.Background()

	e, err := Open(ctx, dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer e.Close()

	tables, err := e.Tables(ctx)
	if err != nil {
		t.Fatalf("tables: %v", err)
	}
	t.Logf("%d tables", len(tables))
	if len(tables) == 0 {
		return
	}
	for i, tb := range tables {
		if i >= 8 {
			t.Logf("  … (%d more)", len(tables)-8)
			break
		}
		t.Logf("  %s.%s", tb.Schema, tb.Name)
	}

	first := tables[0]
	cols, err := e.Columns(ctx, first.Ref())
	if err != nil {
		t.Fatalf("columns(%s.%s): %v", first.Schema, first.Name, err)
	}
	t.Logf("columns of %s.%s:", first.Schema, first.Name)
	for _, c := range cols {
		t.Logf("  %-24s %-16s pk=%-5v auto=%-5v", c.Name, c.Type, c.PrimaryKey, c.AutoGenerated)
	}

	pk, err := e.PrimaryKey(ctx, first.Ref())
	if err != nil {
		t.Fatalf("pk: %v", err)
	}
	t.Logf("primary key: %v", pk)

	rs, err := e.Query(ctx, "SELECT * FROM "+e.QualifiedName(first.Ref())+" LIMIT 3")
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	t.Logf("sample query → %d cols, %d rows", len(rs.Cols), len(rs.Rows))
}
