package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib" // registers the "pgx" driver
)

type pgEngine struct {
	db *sql.DB
}

func openPostgres(ctx context.Context, dsn string) (Engine, error) {
	cfg, err := pgx.ParseConfig(dsn)
	if err != nil {
		return nil, err
	}
	sdb, err := sql.Open("pgx", stdlib.RegisterConnConfig(cfg))
	if err != nil {
		return nil, err
	}
	if err := sdb.PingContext(ctx); err != nil {
		sdb.Close()
		return nil, fmt.Errorf("connecting to postgres: %w", err)
	}
	return &pgEngine{db: sdb}, nil
}

func (e *pgEngine) Close() error             { return e.db.Close() }
func (e *pgEngine) Placeholder(i int) string { return fmt.Sprintf("$%d", i) }

func (e *pgEngine) QuoteIdent(s string) string { return quoteIdentDouble(s) }

func (e *pgEngine) QualifiedName(t TableRef) string {
	if t.Schema != "" {
		return e.QuoteIdent(t.Schema) + "." + e.QuoteIdent(t.Name)
	}
	return e.QuoteIdent(t.Name)
}

func (e *pgEngine) FilterPredicate(quotedCol string, i int) string {
	return fmt.Sprintf("LOWER(%s::text) LIKE LOWER($%d)", quotedCol, i)
}

func (e *pgEngine) Databases(ctx context.Context) ([]string, error) {
	// datallowconn filters out databases that reject connections (e.g. template0),
	// which would otherwise be offered in the switcher but fail on select.
	return queryStrings(ctx, e.db,
		`SELECT datname FROM pg_database WHERE datistemplate = false AND datallowconn ORDER BY datname`)
}

func (e *pgEngine) Tables(ctx context.Context) ([]Table, error) {
	rows, err := e.db.QueryContext(ctx, `
		SELECT schemaname, tablename
		FROM pg_catalog.pg_tables
		WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
		ORDER BY schemaname, tablename`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Table
	for rows.Next() {
		var s, n string
		if err := rows.Scan(&s, &n); err != nil {
			return nil, err
		}
		out = append(out, Table{Schema: s, Name: n})
	}
	return out, rows.Err()
}

func (e *pgEngine) Columns(ctx context.Context, t TableRef) ([]Column, error) {
	schema := t.Schema
	if schema == "" {
		schema = "public"
	}
	rows, err := e.db.QueryContext(ctx, `
		SELECT column_name, data_type, is_nullable, column_default, is_identity
		FROM information_schema.columns
		WHERE table_schema = $1 AND table_name = $2
		ORDER BY ordinal_position`, schema, t.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var cols []Column
	idx := map[string]int{}
	for rows.Next() {
		var name, dtype, nullable, isIdentity string
		var dflt sql.NullString
		if err := rows.Scan(&name, &dtype, &nullable, &dflt, &isIdentity); err != nil {
			return nil, err
		}
		auto := isIdentity == "YES" || (dflt.Valid && strings.HasPrefix(dflt.String, "nextval("))
		idx[name] = len(cols)
		cols = append(cols, Column{
			Name:          name,
			Type:          dtype,
			HasDefault:    dflt.Valid,
			AutoGenerated: auto,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	pk, err := e.PrimaryKey(ctx, t)
	if err != nil {
		return nil, err
	}
	for _, name := range pk {
		if i, ok := idx[name]; ok {
			cols[i].PrimaryKey = true
			cols[i].Unique = true
		}
	}
	uniq, err := e.uniqueColumns(ctx, t)
	if err != nil {
		return nil, err
	}
	for _, name := range uniq {
		if i, ok := idx[name]; ok {
			cols[i].Unique = true
		}
	}
	return cols, nil
}

// uniqueColumns returns columns covered by a UNIQUE constraint (used to annotate
// generated inserts). Bare unique indexes aren't included — constraints are the
// common case and mirror the PrimaryKey query.
func (e *pgEngine) uniqueColumns(ctx context.Context, t TableRef) ([]string, error) {
	schema := t.Schema
	if schema == "" {
		schema = "public"
	}
	return queryStrings(ctx, e.db, `
		SELECT kcu.column_name
		FROM information_schema.table_constraints tc
		JOIN information_schema.key_column_usage kcu
		  ON tc.constraint_name = kcu.constraint_name
		 AND tc.table_schema = kcu.table_schema
		WHERE tc.constraint_type = 'UNIQUE'
		  AND tc.table_schema = $1 AND tc.table_name = $2`, schema, t.Name)
}

func (e *pgEngine) PrimaryKey(ctx context.Context, t TableRef) ([]string, error) {
	schema := t.Schema
	if schema == "" {
		schema = "public"
	}
	return queryStrings(ctx, e.db, `
		SELECT kcu.column_name
		FROM information_schema.table_constraints tc
		JOIN information_schema.key_column_usage kcu
		  ON tc.constraint_name = kcu.constraint_name
		 AND tc.table_schema = kcu.table_schema
		WHERE tc.constraint_type = 'PRIMARY KEY'
		  AND tc.table_schema = $1 AND tc.table_name = $2
		ORDER BY kcu.ordinal_position`, schema, t.Name)
}

// ForeignKeys reads FK constraints from pg_catalog, walking each constraint's
// parallel (conkey, confkey) column arrays by subscript so composite keys keep
// their column order.
func (e *pgEngine) ForeignKeys(ctx context.Context, t TableRef) ([]ForeignKey, error) {
	schema := t.Schema
	if schema == "" {
		schema = "public"
	}
	rows, err := e.db.QueryContext(ctx, `
		SELECT con.conname, att.attname, nsp2.nspname, cl2.relname, att2.attname
		FROM pg_constraint con
		JOIN pg_class cl       ON cl.oid = con.conrelid
		JOIN pg_namespace nsp  ON nsp.oid = cl.relnamespace
		JOIN pg_class cl2      ON cl2.oid = con.confrelid
		JOIN pg_namespace nsp2 ON nsp2.oid = cl2.relnamespace
		JOIN generate_subscripts(con.conkey, 1) AS s(i) ON true
		JOIN pg_attribute att  ON att.attrelid = con.conrelid  AND att.attnum = con.conkey[s.i]
		JOIN pg_attribute att2 ON att2.attrelid = con.confrelid AND att2.attnum = con.confkey[s.i]
		WHERE con.contype = 'f' AND nsp.nspname = $1 AND cl.relname = $2
		ORDER BY con.conname, s.i`, schema, t.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var acc fkAccum
	for rows.Next() {
		var name, col, refSchema, refTable, refCol string
		if err := rows.Scan(&name, &col, &refSchema, &refTable, &refCol); err != nil {
			return nil, err
		}
		acc.add(name, TableRef{Schema: refSchema, Name: refTable}, col, refCol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return acc.result(), nil
}

func (e *pgEngine) Query(ctx context.Context, query string, args ...any) (*ResultSet, error) {
	return scanQuery(ctx, e.db, query, args...)
}

func (e *pgEngine) Exec(ctx context.Context, query string, args ...any) (int64, error) {
	res, err := e.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
