package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	_ "modernc.org/sqlite" // pure-Go driver, registered as "sqlite"
)

type sqliteEngine struct {
	db *sql.DB
}

func openSQLite(ctx context.Context, dsn string) (Engine, error) {
	path := sqlitePath(dsn)
	sdb, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	if err := sdb.PingContext(ctx); err != nil {
		sdb.Close()
		return nil, fmt.Errorf("opening sqlite %q: %w", path, err)
	}
	return &sqliteEngine{db: sdb}, nil
}

// sqlitePath extracts a filesystem path from sqlite:///path, file:path, or a bare path.
func sqlitePath(dsn string) string {
	for _, p := range []string{"sqlite://", "sqlite3://", "file://", "sqlite:", "file:"} {
		if strings.HasPrefix(dsn, p) {
			return strings.TrimPrefix(dsn, p)
		}
	}
	return dsn
}

func (e *sqliteEngine) Close() error         { return e.db.Close() }
func (e *sqliteEngine) UsesSchemas() bool     { return false }
func (e *sqliteEngine) Placeholder(int) string { return "?" }

func (e *sqliteEngine) QuoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

func (e *sqliteEngine) QualifiedName(t TableRef) string { return e.QuoteIdent(t.Name) }

func (e *sqliteEngine) FilterPredicate(quotedCol string, _ int) string {
	return fmt.Sprintf("LOWER(CAST(%s AS TEXT)) LIKE LOWER(?)", quotedCol)
}

func (e *sqliteEngine) Databases(context.Context) ([]string, error) { return nil, nil }

func (e *sqliteEngine) Tables(ctx context.Context) ([]Table, error) {
	rows, err := e.db.QueryContext(ctx,
		`SELECT name FROM sqlite_master
		 WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
		 ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []Table
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			return nil, err
		}
		out = append(out, Table{Name: n})
	}
	return out, rows.Err()
}

func (e *sqliteEngine) Columns(ctx context.Context, t TableRef) ([]Column, error) {
	q := fmt.Sprintf("PRAGMA table_info(%s)", e.QuoteIdent(t.Name))
	rows, err := e.db.QueryContext(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var cols []Column
	pkCount := 0
	for rows.Next() {
		var (
			cid           int
			name, ctype   string
			notnull, pk   int
			dflt          sql.NullString
		)
		if err := rows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pk); err != nil {
			return nil, err
		}
		if pk > 0 {
			pkCount++
		}
		cols = append(cols, Column{
			Name:       name,
			Type:       ctype,
			Nullable:   notnull == 0,
			PrimaryKey: pk > 0,
			HasDefault: dflt.Valid,
			Default:    dflt.String,
		})
	}
	// A lone INTEGER PRIMARY KEY is a rowid alias → auto-generated.
	if pkCount == 1 {
		for i := range cols {
			if cols[i].PrimaryKey && strings.EqualFold(cols[i].Type, "INTEGER") {
				cols[i].AutoGenerated = true
			}
		}
	}
	return cols, rows.Err()
}

func (e *sqliteEngine) PrimaryKey(ctx context.Context, t TableRef) ([]string, error) {
	cols, err := e.Columns(ctx, t)
	if err != nil {
		return nil, err
	}
	var pk []string
	for _, c := range cols {
		if c.PrimaryKey {
			pk = append(pk, c.Name)
		}
	}
	return pk, nil
}

func (e *sqliteEngine) Query(ctx context.Context, query string, args ...any) (*ResultSet, error) {
	return scanQuery(ctx, e.db, query, args...)
}

func (e *sqliteEngine) Exec(ctx context.Context, query string, args ...any) (int64, error) {
	res, err := e.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
