package db

import (
	"context"
	"database/sql"
	"fmt"
	"sort"
	"strconv"
	"strings"

	_ "modernc.org/sqlite" // pure-Go driver, registered as "sqlite"
)

type sqliteEngine struct {
	db *sql.DB
}

func openSQLite(ctx context.Context, dsn string) (Engine, error) {
	path := sqlitePath(dsn)
	sdb, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	if err := sdb.PingContext(ctx); err != nil {
		sdb.Close()
		return nil, fmt.Errorf("opening sqlite %q: %w", path, err)
	}
	return &sqliteEngine{db: sdb}, nil
}

// sqlitePath extracts a filesystem path from sqlite:///path, file:path, or a bare path.
func sqlitePath(dsn string) string {
	for _, p := range []string{"sqlite://", "sqlite3://", "file://", "sqlite:", "file:"} {
		if strings.HasPrefix(dsn, p) {
			return strings.TrimPrefix(dsn, p)
		}
	}
	return dsn
}

func (e *sqliteEngine) Close() error           { return e.db.Close() }
func (e *sqliteEngine) Placeholder(int) string { return "?" }

func (e *sqliteEngine) QuoteIdent(s string) string { return quoteIdentDouble(s) }

func (e *sqliteEngine) QualifiedName(t TableRef) string { return e.QuoteIdent(t.Name) }

func (e *sqliteEngine) FilterPredicate(quotedCol string, _ int) string {
	return fmt.Sprintf("LOWER(CAST(%s AS TEXT)) LIKE LOWER(?)", quotedCol)
}

func (e *sqliteEngine) Databases(context.Context) ([]string, error) { return nil, nil }

func (e *sqliteEngine) Tables(ctx context.Context) ([]Table, error) {
	names, err := queryStrings(ctx, e.db,
		`SELECT name FROM sqlite_master
		 WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
		 ORDER BY name`)
	if err != nil {
		return nil, err
	}
	out := make([]Table, len(names))
	for i, n := range names {
		out[i] = Table{Name: n}
	}
	return out, nil
}

func (e *sqliteEngine) Columns(ctx context.Context, t TableRef) ([]Column, error) {
	q := fmt.Sprintf("PRAGMA table_info(%s)", e.QuoteIdent(t.Name))
	rows, err := e.db.QueryContext(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var cols []Column
	pkCount := 0
	for rows.Next() {
		var (
			cid         int
			name, ctype string
			notnull, pk int
			dflt        sql.NullString
		)
		if err := rows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pk); err != nil {
			return nil, err
		}
		if pk > 0 {
			pkCount++
		}
		cols = append(cols, Column{
			Name:       name,
			Type:       ctype,
			PrimaryKey: pk > 0,
			HasDefault: dflt.Valid,
		})
	}
	// A lone INTEGER PRIMARY KEY is a rowid alias → auto-generated.
	if pkCount == 1 {
		for i := range cols {
			if cols[i].PrimaryKey && strings.EqualFold(cols[i].Type, "INTEGER") {
				cols[i].AutoGenerated = true
			}
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	uniq, err := e.uniqueColumns(ctx, t)
	if err != nil {
		return nil, err
	}
	for i := range cols {
		if cols[i].PrimaryKey || uniq[cols[i].Name] {
			cols[i].Unique = true
		}
	}
	return cols, nil
}

// uniqueColumns returns the set of columns covered by a UNIQUE index (used to
// annotate generated inserts), via PRAGMA index_list + index_info.
func (e *sqliteEngine) uniqueColumns(ctx context.Context, t TableRef) (map[string]bool, error) {
	rows, err := e.db.QueryContext(ctx, fmt.Sprintf("PRAGMA index_list(%s)", e.QuoteIdent(t.Name)))
	if err != nil {
		return nil, err
	}
	var uniqueIdx []string
	for rows.Next() {
		var (
			seq, unique, partial int
			name, origin         string
		)
		if err := rows.Scan(&seq, &name, &unique, &origin, &partial); err != nil {
			rows.Close()
			return nil, err
		}
		// A partial unique index (… WHERE …) doesn't guarantee global uniqueness,
		// so it shouldn't flag its columns as unique.
		if unique == 1 && partial == 0 {
			uniqueIdx = append(uniqueIdx, name)
		}
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return nil, err
	}
	rows.Close()

	out := map[string]bool{}
	for _, idx := range uniqueIdx {
		irows, err := e.db.QueryContext(ctx, fmt.Sprintf("PRAGMA index_info(%s)", e.QuoteIdent(idx)))
		if err != nil {
			return nil, err
		}
		for irows.Next() {
			var seqno, cid int
			var cname sql.NullString
			if err := irows.Scan(&seqno, &cid, &cname); err != nil {
				irows.Close()
				return nil, err
			}
			if cname.Valid {
				out[cname.String] = true
			}
		}
		if err := irows.Err(); err != nil {
			irows.Close()
			return nil, err
		}
		irows.Close()
	}
	return out, nil
}

// PrimaryKey reads just the PK from PRAGMA table_info — deliberately not via
// Columns, which also runs the unique-index PRAGMAs. PrimaryKey is on the hot
// path (every load and scroll fetch); the unique lookup is only wanted for o.
func (e *sqliteEngine) PrimaryKey(ctx context.Context, t TableRef) ([]string, error) {
	rows, err := e.db.QueryContext(ctx, fmt.Sprintf("PRAGMA table_info(%s)", e.QuoteIdent(t.Name)))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var pk []string
	for rows.Next() {
		var (
			cid, notnull, pkFlag int
			name, ctype          string
			dflt                 sql.NullString
		)
		if err := rows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pkFlag); err != nil {
			return nil, err
		}
		if pkFlag > 0 {
			pk = append(pk, name)
		}
	}
	return pk, rows.Err()
}

// ForeignKeys reads FK constraints via PRAGMA foreign_key_list, grouping the
// per-column rows by constraint id. A NULL "to" (a `REFERENCES parent` without an
// explicit column) means the parent's primary key, resolved here.
func (e *sqliteEngine) ForeignKeys(ctx context.Context, t TableRef) ([]ForeignKey, error) {
	rows, err := e.db.QueryContext(ctx, fmt.Sprintf("PRAGMA foreign_key_list(%s)", e.QuoteIdent(t.Name)))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	// PRAGMA foreign_key_list doesn't accept ORDER BY, and the `seq` (column order
	// within a composite key) is only reliable if we sort on it ourselves — so
	// collect the rows and sort by (id, seq) before assembling, rather than trusting
	// the emission order (pg/mysql get this from their query's ORDER BY).
	type fkRow struct {
		id, seq        int
		refTable, from string
		to             string
	}
	var raw []fkRow
	for rows.Next() {
		var id, seq int
		var refTable, from, onUpd, onDel, match string
		var to sql.NullString
		if err := rows.Scan(&id, &seq, &refTable, &from, &to, &onUpd, &onDel, &match); err != nil {
			return nil, err
		}
		raw = append(raw, fkRow{id, seq, refTable, from, to.String})
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sort.SliceStable(raw, func(i, j int) bool {
		if raw[i].id != raw[j].id {
			return raw[i].id < raw[j].id
		}
		return raw[i].seq < raw[j].seq
	})

	var acc fkAccum
	for _, r := range raw {
		// "" RefColumn (a column-less REFERENCES) is resolved to the PK below.
		acc.add(strconv.Itoa(r.id), TableRef{Name: r.refTable}, r.from, r.to)
	}

	out := make([]ForeignKey, 0, len(acc.order))
	for _, fk := range acc.ordered() {
		if err := e.resolveImplicitPK(ctx, fk); err != nil {
			return nil, err
		}
		out = append(out, *fk)
	}
	return out, nil
}

// resolveImplicitPK fills any blank RefColumns (a column-less REFERENCES) from the
// referenced table's primary key, positionally.
func (e *sqliteEngine) resolveImplicitPK(ctx context.Context, fk *ForeignKey) error {
	blank := false
	for _, c := range fk.RefColumns {
		if c == "" {
			blank = true
		}
	}
	if !blank {
		return nil
	}
	pk, err := e.PrimaryKey(ctx, fk.RefTable)
	if err != nil {
		return err
	}
	for i := range fk.RefColumns {
		if fk.RefColumns[i] == "" && i < len(pk) {
			fk.RefColumns[i] = pk[i]
		}
	}
	return nil
}

func (e *sqliteEngine) Query(ctx context.Context, query string, args ...any) (*ResultSet, error) {
	return scanQuery(ctx, e.db, query, args...)
}

func (e *sqliteEngine) Exec(ctx context.Context, query string, args ...any) (int64, error) {
	res, err := e.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
