package db

import (
	"context"
	"path/filepath"
	"testing"
)

func newTestDB(t *testing.T) Engine {
	t.Helper()
	ctx := context.Background()
	e, err := Open(ctx, filepath.Join(t.TempDir(), "t.db"))
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	t.Cleanup(func() { e.Close() })
	mustExec(t, e, `CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, email TEXT)`)
	mustExec(t, e, `INSERT INTO users (name, email) VALUES ('Ada','ada@x.io'), ('Linus', NULL)`)
	return e
}

func mustExec(t *testing.T, e Engine, q string) {
	t.Helper()
	if _, err := e.Exec(context.Background(), q); err != nil {
		t.Fatalf("exec %q: %v", q, err)
	}
}

func TestSQLiteColumnsUnique(t *testing.T) {
	ctx := context.Background()
	e, err := Open(ctx, filepath.Join(t.TempDir(), "u.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer e.Close()
	mustExec(t, e, `CREATE TABLE u (id INTEGER PRIMARY KEY, email TEXT UNIQUE, name TEXT)`)

	cols, err := e.Columns(ctx, TableRef{Name: "u"})
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]Column{}
	for _, c := range cols {
		got[c.Name] = c
	}
	if c := got["id"]; !c.PrimaryKey || !c.Unique || !c.AutoGenerated {
		t.Errorf("id: %+v — want PK+Unique+AutoGenerated", c)
	}
	if c := got["email"]; !c.Unique || c.PrimaryKey {
		t.Errorf("email: %+v — want Unique, not PK", c)
	}
	if c := got["name"]; c.Unique {
		t.Errorf("name: %+v — want not Unique", c)
	}
}

func TestSQLiteIntrospectionAndQuery(t *testing.T) {
	e := newTestDB(t)
	ctx := context.Background()

	tbls, err := e.Tables(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(tbls) != 1 || tbls[0].Name != "users" {
		t.Fatalf("tables: %+v", tbls)
	}

	ref := TableRef{Name: "users"}
	cols, err := e.Columns(ctx, ref)
	if err != nil {
		t.Fatal(err)
	}
	if len(cols) != 3 {
		t.Fatalf("want 3 cols, got %d", len(cols))
	}
	if !cols[0].PrimaryKey || !cols[0].AutoGenerated {
		t.Fatalf("id should be PK + auto-generated rowid alias: %+v", cols[0])
	}

	pk, err := e.PrimaryKey(ctx, ref)
	if err != nil {
		t.Fatal(err)
	}
	if len(pk) != 1 || pk[0] != "id" {
		t.Fatalf("pk: %v", pk)
	}

	rs, err := e.Query(ctx, "SELECT id, name, email FROM users ORDER BY id")
	if err != nil {
		t.Fatal(err)
	}
	if len(rs.Rows) != 2 {
		t.Fatalf("want 2 rows, got %d", len(rs.Rows))
	}
	if rs.Rows[1][2] != nil {
		t.Fatalf("Linus.email should scan as nil (NULL), got %v", rs.Rows[1][2])
	}
}
